branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Not really necessary, just to get a green badge on “master”
    - master
    - v0.8
language: rust
os: linux
dist: focal
addons:
  apt:
    sources:
    - sourceline: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
      key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
    - clang-11
    - cmake
    - qemu-user
before_script:
  - printenv
  - whereis clang && clang --version
  # remove clang-16 path from PATH
  - export PATH=$(echo $PATH | sed -e 's|:/usr/local/clang-16.0.0/bin||')
  # setup clang-11 as default clang
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-11 100
  - whereis clang && clang --version

env:
  global:
    - RUST_BACKTRACE=1
    # Pinned to this particular nightly version because of core_io. This can be
    # re-pinned whenever core_io is updated to the latest nightly.
    - CORE_IO_NIGHTLY=nightly-2021-03-25
jobs:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu ZLIB_INSTALLED=true AES_NI_SUPPORT=true
      rust: nightly-2021-03-25
    - env: TARGET=x86_64-fortanix-unknown-sgx
      rust: stable
    - env: TARGET=aarch64-unknown-linux-musl
      rust: stable
    - env: TARGET=x86_64-unknown-linux-gnu ZLIB_INSTALLED=true AES_NI_SUPPORT=true
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu ZLIB_INSTALLED=true AES_NI_SUPPORT=true
      rust: beta
    - env: TARGET=x86_64-unknown-linux-gnu ZLIB_INSTALLED=true AES_NI_SUPPORT=true
      rust: stable
script:
  - ./ct.sh
