name: CI

on:
  push:
    branches:
      - 'v0.*'
      - staging
      - trying
  pull_request:
    branches:
      - master
      - 'v0.*'
  merge_group:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10

jobs:
  test:
    name: Test
    strategy:
      matrix:
        include:
          - rust: stable
            target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
          - rust: stable
            target: x86_64-fortanix-unknown-sgx
            os: ubuntu-20.04
          - rust: stable
            target: x86_64-pc-windows-msvc
            os: windows-latest
          - rust: stable
            target: aarch64-unknown-linux-musl
            os: ubuntu-20.04
          - rust: stable
            target: x86_64-apple-darwin
            os: macos-latest
          - rust: beta
            target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
          - rust: nightly
            target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      if: matrix.target == 'aarch64-unknown-linux-musl'
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user

    # python version is read from .python-version
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        cache: 'pip'
        cache-dependency-path: |
          mbedtls-sys/vendor/scripts/basic.requirements.txt
          mbedtls-sys/vendor/scripts/driver.requirements.txt

    - name: Install python dependencies
      run: python3 -m pip install -r mbedtls-sys/vendor/scripts/basic.requirements.txt

    - name: Cache Dependencies
      uses: Swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894
      with:
        key: ${{ matrix.rust }}

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
        override: true

    - name: Run tests
      run: |
        ./ci_tools.sh
        ./ci.sh
      env:
        TRAVIS_RUST_VERSION: ${{ matrix.rust }}
        TARGET: ${{ matrix.target }}
        ZLIB_INSTALLED: ${{ matrix.target == 'x86_64-unknown-linux-gnu' && 'true' || '' }}
        AES_NI_SUPPORT: ${{ matrix.target == 'x86_64-unknown-linux-gnu' && 'true' || '' }}
      shell: bash
  ci-success:
    name: ci
    if: always()
    needs:
      - test
    runs-on: ubuntu-20.04
    steps:
      - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
      - name: Done
        run: exit 0